import React, { useState } from "react";
import Navbar from "../Navbar";
import FootprintCard from "../FootprintCard";
import FlightsFootprint from "../FlightsFootprint";
import VehicleFootprint from "../VehicleFootprint";
import ElectricityFootprint from "../ElectricityFootprint";

function Calc() {

    const [chooseFootprint, setChooseFootprint] = useState();

    function clickFlight() {
        setChooseFootprint(<FlightsFootprint />);
    }

    function clickVehicle() {
        setChooseFootprint(<VehicleFootprint />);   
    }

    function clickElectricity() {
        setChooseFootprint(<ElectricityFootprint />);   
    }

    return(
        <div>
            <Navbar active = "calc"/>
            <div className="calc-one">
                <div className="in">
                    <h1>Carbon Footprint Calculator</h1>
                    <p>Identify and calculate all the carbon emissions you or your company <br /> are responsible for with the help of our carbon footprint calculator.</p>
                </div>
            </div>
            <div className="calc-two">
                <h1>Choose from the following footprints</h1>
            </div>
            <div id="one" className="footprintContainer">
                <div id="flight" onClick={clickFlight}><FootprintCard svg="flight-svg.svg" title="Flights Footprint" desc="Use this calculator to compute carbon footprint generated by travel by airplane" /></div>
                <div id="vehicle" onClick={clickVehicle}><FootprintCard svg="vehicle-svg.svg" title="Vehicle Footprint" desc="Use this calculator to compute carbon footprint generated by travel by vehicles" /></div>
                <div id="electricity" onClick={clickElectricity}><FootprintCard svg="electricity-svg.svg" title="Electricity Footprint" desc="Use this calculator to compute carbon footprint generated by electricity comsumption" /></div>
            </div>
            <div className="calc-three">
                {chooseFootprint}
            </div>
            <div className="calc-four"></div>
        </div>
    );
}

export default Calc;